### ISSUE TITLE
simple "temporary" GXP gpf to S.SET gpf formatter 

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/APPL-Tools#68]
Until we get PLIO updated (perhaps the issue better defined), https://github.com/USGS-Astrogeology/plio/issues/24 , can we implement a simple gpf GXP -> SSET routine? I think this could be stand-alone or perhaps a function in https://github.com/USGS-Astrogeology/APPL-Tools/blob/master/SurfaceFit/surface_fit_pc_align.py  (which is where we currently need support for GXP gpfs).

Using an image is a horrible way to explain this but maybe it will help.
![GXP_gpf_toSSET](https://user-images.githubusercontent.com/3095138/118897425-19708180-b8bf-11eb-8776-29de5ed22c1a.png)

Or see the "before" GXP file (renamed to *.txt) and the after conversion to SSET style (now works in surface_fit* script/PLIO)

[before_fromGXP.gpf.txt](https://github.com/USGS-Astrogeology/APPL-Tools/files/6511966/before_fromGXP.gpf.txt)
[convert_toSSET_after.gpf.txt](https://github.com/USGS-Astrogeology/APPL-Tools/files/6511967/convert_toSSET_after.gpf.txt)

**Comment by dpmayerUSGS** [comment]
Are you asking for a standalone utility to convert GXP-style GPFs into the legacy Socet Set format?

This has (sort of) been implemented in #73, taking advantage of newly added support for reading GXP-style GPFs in `plio`. A user can pass a GXP-style GPF as input to `surface_fit_pc_align.py` or `gpf_transform.py` using the `--gxp` commandline option. The scripts will do their thing as usual, and the output GPF file will be in the legacy Socet Set format.

**Comment by thareUSGS** [comment]
No - I am good at just supporting the surface fit workflow.  I guess we could post a wiki page or jupyter notebook on how to do that just using PLIO (right?). Perhaps showing how to convert GXP to ISIS also? A future training task for me.

**Comment by thareUSGS** [comment]
So I guess we can close this.
